services:
  # 自己証明書アーキの保管
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
      - "3001"
      - "3002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development