name: Deploy to Xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Package application
      run: |
        tar -czf app.tar.gz \
        --exclude=.git \
        --exclude=.github \
        --exclude=docker-compose \
        --exclude=drawio \
        --exclude=manuals \
        --exclude=node_modules \
        --exclude=terraform \
        .

    - name: Deploy application
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 2222
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "app.tar.gz"
        target: "/home/appuser/projects"

    - name: Restart application with Docker Compose
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 2222
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/appuser/projects
          tar -xzf app.tar.gz
          rm -f app.tar.gz
          docker-compose down || true
          docker-compose up -d --build
