name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.REGION_NAME }}

    - name: Build Docker
      run: |
            docker build -t ${{ secrets.APP_NAME }}:latest .

    - name: Change Docker Image Tag
      run:  |
            docker tag ${{ secrets.APP_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION_NAME }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest

    - name: AWS ECR Push
      run:  |
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION_NAME }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest