name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION_NAME }}

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.REGION_NAME }} \
        | docker login --username AWS --password-stdin ${{ secrets.AWS_PROJECT_NAME }}.dkr.ecr.${{ secrets.REGION_NAME }}.amazonaws.com

    - name: Build Docker
      run: |
            docker build -t ${{ secrets.APP_NAME }}:latest .

    - name: Change Docker Image Tag
      run:  |
            docker tag ${{ secrets.APP_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION_NAME }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest

    - name: AWS ECR Push
      run:  |
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION_NAME }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest